#### Importing necessary libraries

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
df1 = pd.read_excel('model/data/data-welding.xlsx', sheet_name='Sheet1')
df2 = pd.read_excel('model/data/data-welding.xlsx', sheet_name='Sheet2')

In [3]:
df1.head()

Weld No.  V  A  S  N  Bead height (H)  Bead width (W)  Bead Penetration (P)
0         1 -1 -1 -1 -1             2.38           10.55                  3.94
1         2  1 -1 -1 -1             2.54           12.43                  5.08
2         3 -1  1 -1 -1             3.07            9.76                  5.12
3         4  1  1 -1 -1             2.79           13.14                  6.40
4         5 -1 -1  1 -1             2.03           10.27                  3.05

In [4]:
df2

Sl.No                PARAMETERS    Units Notation  value(-2)  value(-1)  \
0      1                   Current  Amperes        A        250      325.0   
1      2               Arc Voltage    Volts        V         22       22.5   
2      3              Travel speed   mm/sec        S          6        9.0   
3      4  Nozzle to plate distance       Mm        N         20       23.5   

   value(0)  value(1)  value(2)  
0       400     475.0       550  
1        29      32.5        36  
2        12      15.0        18  
3        27      30.5        34

In [5]:
df2 = df2.set_index('Notation')
df2

Sl.No                PARAMETERS    Units  value(-2)  value(-1)  \
Notation                                                                   
A             1                   Current  Amperes        250      325.0   
V             2               Arc Voltage    Volts         22       22.5   
S             3              Travel speed   mm/sec          6        9.0   
N             4  Nozzle to plate distance       Mm         20       23.5   

          value(0)  value(1)  value(2)  
Notation                                
A              400     475.0       550  
V               29      32.5        36  
S               12      15.0        18  
N               27      30.5        34

In [6]:
data = df1.copy()

In [7]:
data = data.astype(object)
df2 = df2.astype(object)

In [8]:
for i in range(len(df1)):
    for col in ['V', 'A', 'S', 'N']:
        data.loc[i, col] = df2[f'value({str(int(df1[col][i]))})'][col]

In [9]:
for col in data.columns:
    if col == 'Weld No.':
        data[col] = data[col].astype('int64')
        continue
    data[col] = data[col].astype('float64')

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Weld No.              31 non-null     int64  
 1   V                     31 non-null     float64
 2   A                     31 non-null     float64
 3   S                     31 non-null     float64
 4   N                     31 non-null     float64
 5   Bead height (H)       31 non-null     float64
 6   Bead width (W)        31 non-null     float64
 7   Bead Penetration (P)  31 non-null     float64
dtypes: float64(7), int64(1)
memory usage: 2.1 KB


In [11]:
data.head()

Weld No.     V      A     S     N  Bead height (H)  Bead width (W)  \
0         1  22.5  325.0   9.0  23.5             2.38           10.55   
1         2  32.5  325.0   9.0  23.5             2.54           12.43   
2         3  22.5  475.0   9.0  23.5             3.07            9.76   
3         4  32.5  475.0   9.0  23.5             2.79           13.14   
4         5  22.5  325.0  15.0  23.5             2.03           10.27   

   Bead Penetration (P)  
0                  3.94  
1                  5.08  
2                  5.12  
3                  6.40  
4                  3.05

In [12]:
data.to_excel('model/data/data_replaced.xlsx', index=False)

In [13]:
df1.head()

Weld No.  V  A  S  N  Bead height (H)  Bead width (W)  Bead Penetration (P)
0         1 -1 -1 -1 -1             2.38           10.55                  3.94
1         2  1 -1 -1 -1             2.54           12.43                  5.08
2         3 -1  1 -1 -1             3.07            9.76                  5.12
3         4  1  1 -1 -1             2.79           13.14                  6.40
4         5 -1 -1  1 -1             2.03           10.27                  3.05

In [14]:
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

In [15]:
X = data.iloc[:, 1:5].values
Y = data.iloc[:, -3:].values

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=316)

In [17]:
regressor = XGBRegressor()
regressor.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [18]:
y_pred = regressor.predict(X_test)

In [19]:
y_pred

array([[ 3.0605316,  8.962853 ,  5.332557 ],
       [ 1.6624138, 10.807027 ,  2.8025804],
       [ 2.0342035, 10.7027445,  4.0859714],
       [ 2.978788 , 12.786759 ,  5.806867 ],
       [ 1.8098342,  9.049013 ,  3.023615 ],
       [ 2.0185375, 11.0030365,  3.9628763],
       [ 2.1430464,  9.755803 ,  3.8631697]], dtype=float32)

In [20]:
y_test

array([[ 3.23,  9.48,  7.31],
       [ 2.08,  9.74,  2.08],
       [ 1.96, 10.4 ,  4.34],
       [ 2.79, 13.14,  6.4 ],
       [ 2.09,  8.08,  2.6 ],
       [ 1.93, 11.4 ,  3.94],
       [ 1.98,  9.26,  3.59]])

In [21]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7848029133381121

In [22]:
test_data = pd.read_excel('model/data/data-welding.xlsx', sheet_name='Sheet3')
test_data

Weld no.     V    A   S     N     H      W     P
0         5  25.5  325  15  23.5  2.03  10.27  3.05
1         8  32.5  475  15  23.5  1.99   9.42  5.37
2        16  32.5  475  15  30.5  3.05  10.58  4.19
3        23  29.0  400  12  20.0  1.96  10.40  4.34
4        31  29.0  400  12  27.0  1.94  10.72  3.68

In [23]:
pred = regressor.predict(test_data.iloc[:, 1:5])
pred

array([[ 2.0312629, 10.270511 ,  3.0516596],
       [ 1.9897397,  9.421179 ,  5.369852 ],
       [ 3.0491655, 10.578496 ,  4.192153 ],
       [ 2.0342035, 10.7027445,  4.0859714],
       [ 2.0185375, 11.0030365,  3.9628763]], dtype=float32)

In [24]:
actual = test_data.iloc[:, -3:]
actual

H      W     P
0  2.03  10.27  3.05
1  1.99   9.42  5.37
2  3.05  10.58  4.19
3  1.96  10.40  4.34
4  1.94  10.72  3.68

In [25]:
percentage_error = (pred - actual) / actual * 100
percentage_error

H         W         P
0  0.062211  0.004972  0.054413
1 -0.013083  0.012514 -0.002755
2 -0.027361 -0.014216  0.051384
3  3.785894  2.911005 -5.853195
4  4.048326  2.640266  7.686857

In [26]:
predicted = regressor.predict(X)
df_xgb = pd.DataFrame(predicted, columns=['height', 'width', 'penetration'])
df_xgb.to_excel('model/data/xgboost.xlsx', index=False)

In [27]:
# filename = 'model_xgboost.sav'
# regressor.save_model(f'model/saved/{filename}')

In [28]:
import joblib
joblib.dump(regressor, 'model/saved/model_xgboost.pkl') 
xgb_from_joblib = joblib.load('model/saved/model_xgboost.pkl') 
xgb_from_joblib.predict(X_test)

array([[ 3.0605316,  8.962853 ,  5.332557 ],
       [ 1.6624138, 10.807027 ,  2.8025804],
       [ 2.0342035, 10.7027445,  4.0859714],
       [ 2.978788 , 12.786759 ,  5.806867 ],
       [ 1.8098342,  9.049013 ,  3.023615 ],
       [ 2.0185375, 11.0030365,  3.9628763],
       [ 2.1430464,  9.755803 ,  3.8631697]], dtype=float32)

## Graphs

In [29]:
import plotly.express as px
fig = px.scatter(data, x="V", y=["Bead height (H)", "Bead width (W)", "Bead Penetration (P)"], trendline="lowess") 
# LOESS (locally estimated scatterplot smoothing) and LOWESS (locally weighted scatterplot smoothing)
fig.show()

In [30]:
fig = px.scatter(data, x="A", y=["Bead height (H)", "Bead width (W)", "Bead Penetration (P)"], trendline="lowess")
fig.show()

In [31]:
fig = px.scatter(data, x="S", y=["Bead height (H)", "Bead width (W)", "Bead Penetration (P)"], trendline="lowess")
fig.show()

In [32]:
fig = px.scatter(data, x="N", y=["Bead height (H)", "Bead width (W)", "Bead Penetration (P)"], trendline="lowess")
fig.show()

In [33]:
@np.vectorize
def f1(A, N):
    return regressor.predict([[0, A, 0, N]])[0][0]

@np.vectorize
def f2(S, N):
    return regressor.predict([[0, 0, S, N]])[0][0]

@np.vectorize
def f3(V, A):
    return regressor.predict([[V, A, 0, 0]])[0][1]

@np.vectorize
def f4(V, S):
    return regressor.predict([[V, 0, S, 0]])[0][1]

In [34]:
import plotly.graph_objects as go

In [35]:
x = data['A'].sort_values()
y = data['N'].sort_values()
xx, yy = np.meshgrid(x, y)
zz = f1(xx, yy)

fig = go.Figure(data =
    go.Surface(
        z=zz,
        x=x,
        y=y
    ))
fig.update_layout(scene = dict(
                    xaxis_title='A',
                    yaxis_title='N',
                    zaxis_title='H'))
fig.show()

In [36]:
x = data['S'].sort_values()
y = data['N'].sort_values()
xx, yy = np.meshgrid(x, y)
zz = f2(xx, yy)

fig = go.Figure(data =
    go.Surface(
        z=zz,
        x=x,
        y=y
    ))
fig.update_layout(scene = dict(
                    xaxis_title='S',
                    yaxis_title='N',
                    zaxis_title='H'))
fig.show()

In [37]:
x = data['V'].sort_values()
y = data['A'].sort_values()
xx, yy = np.meshgrid(x, y)
zz = f3(xx, yy)

fig = go.Figure(data =
    go.Surface(
        z=zz,
        x=x,
        y=y
    ))
fig.update_layout(scene = dict(
                    xaxis_title='V',
                    yaxis_title='A',
                    zaxis_title='W'))
fig.show()

In [38]:
x = data['V'].sort_values()
y = data['S'].sort_values()
xx, yy = np.meshgrid(x, y)
zz = f4(xx, yy)

fig = go.Figure(data =
    go.Surface(
        z=zz,
        x=x,
        y=y
    ))
fig.update_layout(scene = dict(
                    xaxis_title='V',
                    yaxis_title='S',
                    zaxis_title='W'))
fig.show()

### Using other models

In [39]:
from ml_models import Models
models = Models(X, Y)

In [40]:
models.linear_regression()
models.score

0.7297698019547071

In [41]:
models.ploynomial_regression()
models.score

-1.852414208233923

In [42]:
models.decision_tree()
models.score

0.4032027914144498

In [43]:
models.random_forest()
models.score

0.6279973975172316

In [44]:
models.lasso_regression()
models.score

0.5259543439968953

In [45]:
models.ridge_regression()
models.score

0.7292702112022281

### Comparison Graphs

In [46]:
def plot_comparison_graph(df1, df2, model_name):
    df_height = pd.DataFrame({'height_exp': df1.height, f'height_{model_name}': df2.height})
    fig_height = px.line(df_height, markers=True, width=600, height=300)
    df_width = pd.DataFrame({'width_exp': df1.width, f'width_{model_name}': df2.width})
    fig_width = px.line(df_width, markers=True, width=600, height=300)
    df_penetration = pd.DataFrame({'penetration_exp': df1.penetration, f'penetration_{model_name}': df2.penetration})
    fig_penetration = px.line(df_penetration, markers=True, width=600, height=300)

    return fig_height, fig_width, fig_penetration
    

### XGBoost

In [47]:
exp_data = pd.read_excel('model/data/exp_data.xlsx').iloc[:, 5:]
fig_height, fig_width, fig_penetration = plot_comparison_graph(exp_data, df_xgb, model_name='xgb')
fig_height.show()
fig_width.show()
fig_penetration.show()

### Linear Regression

In [48]:
df_lr = pd.read_excel('model/data/linear_regression.xlsx')
fig_height, fig_width, fig_penetration = plot_comparison_graph(exp_data, df_lr, model_name='lr')
fig_height.show()
fig_width.show()
fig_penetration.show()

### Polynomial Regression

In [49]:
df_poly = pd.read_excel('model/data/polynomial_regression.xlsx')
fig_height, fig_width, fig_penetration = plot_comparison_graph(exp_data, df_poly, model_name='pr')
fig_height.show()
fig_width.show()
fig_penetration.show()

### Decision Tree

In [50]:
df_dt = pd.read_excel('model/data/decision_tree_regression.xlsx')
fig_height, fig_width, fig_penetration = plot_comparison_graph(exp_data, df_dt, model_name='dt')
fig_height.show()
fig_width.show()
fig_penetration.show()

### Random Forest

In [51]:
df_rf = pd.read_excel('model/data/random_forest_regression.xlsx')
fig_height, fig_width, fig_penetration = plot_comparison_graph(exp_data, df_rf, model_name='dt')
fig_height.show()
fig_width.show()
fig_penetration.show()

### Lasso Regression

In [52]:
df_lasso = pd.read_excel('model/data/lasso_regression.xlsx')
fig_height, fig_width, fig_penetration = plot_comparison_graph(exp_data, df_lasso, model_name='lasso')
fig_height.show()
fig_width.show()
fig_penetration.show()

### Ridge Regression

In [53]:
df_rigde = pd.read_excel('model/data/ridge_regression.xlsx')
fig_height, fig_width, fig_penetration = plot_comparison_graph(exp_data, df_rigde, model_name='ridge')
fig_height.show()
fig_width.show()
fig_penetration.show()